export type EventKey = keyof typeof EVENT_KEY;
export const EVENT_KEY = {
  API_PROXY_INIT: 'API_PROXY_INIT',
  API_PROXY_OPEN: 'API_PROXY_OPEN', // 开启代理
  API_PROXY_DEVTOOL_INIT: 'API_PROXY_DEVTOOL_INIT', // devtool初始化
  API_PROXY_WEBSITE_UPDATE: 'API_PROXY_WEBSITE_UPDATE', // 代理切换
  API_PROXY_APIPROXY_UPDATE: 'API_PROXY_APIPROXY_UPDATE', //代理api新建或更新
  API_PROXY_APIPROXY_DELETE: 'API_PROXY_APIPROXY_DELETE', // 删除api
};
